### ISSUE TITLE
More Features with Project Evoli

### ISSUE THREAD

**Issue by LopeKinz** [DamagingRose/Rose-RAT#5]
Project Evoli is a Python "Extention" To easily create or upgrade Rats. It has a ton of features that can be copied and added into your own rat. (But you need to give credits)

WARNING : Project Evoli has as alot of desturctive Features!

https://github.com/LopeKinz/project-evoli

**Comment by Gumbobrot** [comment]
# Probably the end of DamagingRose...

That's a cool idea but we have discontinued this project for a unknown time period, because pierro and I decided to leave this community. We don't want to have anything to do with what our community does. And yeah, our tools are used for bad things, I mean really bad things. We don't want to be the creators or reasons of that anymore. I hope you can understand that, but we decided to go our own ways, especially I, because what I have heard from **my** community in the last weeks was just disgusting,

Have a nice day to everybody who reads this! :)

**Comment by Gumbobrot** [comment]
Don't really know if pierro hops back in after the holidays, but I will need my time.
